### ISSUE TITLE
Error while executing

### ISSUE THREAD

**Issue by gabrielqpx** [chmccarthy/Pangloss#3]
I have some issues executing Pangloss. I have all the paths declared in the config file, but the following error shows up:
$ python Pangloss.py --pred --busco --refine --ips --go --yn00 --plots config_asp.ini
/usr/lib/python2.7/dist-packages/Bio/SearchIO/__init__.py:211: BiopythonExperimentalWarning: Bio.SearchIO is an experimental submodule which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)
Traceback (most recent call last):
  File "Pangloss.py", line 631, in <module>
    main()
  File "Pangloss.py", line 531, in main
    PanGuessHandler(*panguess_args)
  File "Pangloss.py", line 151, in PanGuessHandler
    exonerate_genes = PanGuess.RunExonerate(cmds, cores)
  File ".../Pangloss/Pangloss/PanGuess.py", line 132, in RunExonerate
    genes = farm.map(ExonerateCmdLine, cmds)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AssertionError

As I thought this could be an exonerate bug, I tried the --no_exonerate flag, but another bug appears:
$ python Pangloss.py --pred --busco --refine --ips --go --yn00 --plots --no_exonerate config_asp.ini
/usr/lib/python2.7/dist-packages/Bio/SearchIO/__init__.py:211: BiopythonExperimentalWarning: Bio.SearchIO is an experimental submodule which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)
Traceback (most recent call last):
  File "Pangloss.py", line 631, in <module>
    main()
  File "Pangloss.py", line 531, in main
    PanGuessHandler(*panguess_args)
  File "Pangloss.py", line 167, in PanGuessHandler
    genemark_gtf = PanGuess.RunGeneMark(genome, gm_path, gm_branch, cores)
  File ".../Pangloss/Pangloss/PanGuess.py", line 171, in RunGeneMark
    sp.call([gm_path, "--ES", "--fungus", "--cores", cores, "--sequence", genome])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Could you please help me solve this? I really need this analysis for an upcoming article.
Thank you very much for your attention

**Comment by chmccarthy** [comment]
Hi Gabriel,

I think you're getting this error because Pangloss can't find either Exonerate or GeneMark-ES (see for example [this S/O link](https://stackoverflow.com/questions/901982/python-oserror-errno-2) as to why Python spits out this type of error). This may be because you don't have either program installed or because the paths to their respective executables (exonerate and gmes_petap.pl) aren't properly defined in your config_asp.ini file. Links to all of Pangloss' dependencies are [included in the manual](https://github.com/chmccarthy/Pangloss/blob/master/Pangloss_Manual.pdf).

**Comment by bioinfokushwaha** [comment]
Hi
I am Facing this error given below for Pangloss. All dependencies working fine independently  


(base) phdstudent@server1:~/Pangloss-master$ python Pangloss.py
  File "Pangloss.py", line 334
    print "{0}, {1} has unusual frameshift mutation and can't be run through yn00.".format(e, cluster)
          ^
SyntaxError: invalid syntax

Please help me to fix it
